CREATE TABLE members
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name     VARCHAR(255),
    last_name      VARCHAR(255),
    gender         VARCHAR(32),
    address        VARCHAR(255),
    phone_number   VARCHAR(255),
    birth_date     DATE,
    status         VARCHAR(32),
    email          VARCHAR(255),
    email_verified BOOLEAN,
    avatar         BYTEA,
    username       VARCHAR(255),
    password       VARCHAR(255),

    CONSTRAINT pk_members PRIMARY KEY (id)
)