CREATE TABLE packages
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     VARCHAR(255),
    duration INTEGER,
    price    DECIMAL,
    currency VARCHAR(3),

    CONSTRAINT pk_packages PRIMARY KEY (id)
)