CREATE TABLE trainers
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name   VARCHAR(255),
    last_name    VARCHAR(255),
    gender       VARCHAR(32),
    phone_number VARCHAR(255),
    address      VARCHAR(255),
    hire_date    DATE,
    email        VARCHAR(255),
    avatar       BYTEA,
    username     VARCHAR(255),
    password     VARCHAR(255),

    CONSTRAINT pk_trainers PRIMARY KEY (id)
)