CREATE TABLE exercises
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(255),
    instructions VARCHAR(255),

    CONSTRAINT pk_exercises PRIMARY KEY (id)
)