INSERT INTO exercise (name, body_part, category, instructions)
VALUES ('Bench Press', 'CHEST', 'BARBELL',
        'Lie on a flat bench with a barbell at chest level. Grip the barbell slightly wider than shoulder-width apart. Lift the barbell off the rack and lower it to your chest. Push the barbell back up to the starting position.'),
       ('Bench Press', 'CHEST', 'DUMBBELL',
        'Lie on a flat bench with a dumbbell in each hand, palms facing forward. Extend your arms straight up over your chest. Lower the dumbbells down towards your chest, then push them back up to the starting position.'),
       ('Incline Bench Press', 'CHEST', 'BARBELL',
        'Lie on an incline bench with a barbell at chest level. Grip the barbell slightly wider than shoulder-width apart. Lift the barbell off the rack and lower it to your upper chest. Push the barbell back up to the starting position.'),
       ('Incline Bench Press', 'CHEST', 'DUMBBELL',
        'Lie on an incline bench with a dumbbell in each hand, palms facing forward. Extend your arms straight up over your chest. Lower the dumbbells down towards your upper chest, then push them back up to the starting position.'),
       ('Chest Press', 'CHEST', 'MACHINE',
        'Sit on a chest press machine with your back against the backrest. Grab the handles with your palms facing forward. Push the handles forward until your arms are fully extended, then bring them back towards your chest.'),
       ('Squat', 'LEGS', 'BARBELL',
        'Stand with your feet shoulder-width apart. Hold a barbell across your upper back. Bend your knees and hips, lowering your body towards the ground. Push through your heels to return to a standing position.'),
       ('Lunge', 'LEGS', 'BARBELL',
        'Stand with your feet hip-width apart and a barbell across your upper back. Take a step forward with one leg and lower your body, bending both knees to approximately 90 degrees. Push through your front heel to return to the starting position. Alternate legs.'),
       ('Lunge', 'ARMS', 'DUMBBELL',
        'Stand with your feet hip-width apart, holding a dumbbell in each hand at your sides. Take a step forward with one leg and lower your body, bending both knees to approximately 90 degrees. Push through your front heel to return to the starting position. Alternate legs.'),
       ('Bicep Curl', 'ARMS', 'BARBELL',
        'Stand with your feet shoulder-width apart, holding a barbell with an underhand grip, arms extended straight down. Keeping your upper arms stationary, curl the barbell up towards your shoulders. Lower the barbell back down to the starting position.'),
       ('Bicep Curl', 'ARMS', 'DUMBBELL',
        'Stand with your feet shoulder-width apart, holding a dumbbell in each hand, palms facing forward. Keeping your upper arms stationary, curl the dumbbells up towards your shoulders. Lower the dumbbells back down to the starting position.'),
       ('Overhead Press', 'SHOULDERS', 'BARBELL',
        'Stand with your feet shoulder-width apart, holding a barbell at shoulder level, palms facing forward. Press the barbell overhead, fully extending your arms. Lower the barbell back down to shoulder level.'),
       ('Seated Overhead Press', 'SHOULDERS', 'BARBELL',
        'Sit on a bench with a backrest, holding a barbell at shoulder level, palms facing forward. Press the barbell overhead, fully extending your arms. Lower the barbell back down to shoulder level.'),
       ('Deadlift', 'BACK', 'BARBELL',
        'Stand with your feet hip-width apart, holding a barbell in front of your thighs, palms facing your body. Keeping your back straight, hinge at the hips and lower the barbell towards the ground, maintaining a slight bend in your knees. Lift the barbell back up by extending your hips and straightening your back.'),
       ('Bent-Over Row', 'BACK', 'BARBELL',
        'Stand with your feet shoulder-width apart, knees slightly bent, and bend forward at the hips, keeping your back straight. Hold a barbell with an overhand grip, arms extended straight down. Pull the barbell up towards your lower chest, squeezing your shoulder blades together. Lower the barbell back down to the starting position.'),
       ('Pull Up', 'BACK', 'BODY_WEIGHT',
        'Hang from a pull-up bar with your palms facing away from you, hands slightly wider than shoulder-width apart. Pull your body up until your chin is above the bar, then lower yourself back down.'),
       ('Seated Row', 'BACK', 'MACHINE',
        'Sit on a seated row machine with your feet resting on the footplates. Grasp the handles with your arms extended, palms facing each other. Pull the handles towards your body, squeezing your shoulder blades together. Return to the starting position with control.'),
       ('Triceps Extension', 'ARMS', 'MACHINE',
        'Sit on a triceps extension machine with your back against the backrest. Grab the handles with your palms facing down. Extend your arms downward, fully straightening your elbows. Return to the starting position by bending your elbows.'),
       ('Skullcrusher', 'ARMS', 'BARBELL',
        'Lie on a flat bench with a barbell in your hands, arms extended straight up over your chest. Lower the barbell towards your forehead, bending your elbows. Extend your arms back up to the starting position.')