CREATE TABLE IF NOT EXISTS package
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     VARCHAR(255) NOT NULL UNIQUE,
    duration INTEGER DEFAULT 365 CHECK (duration > 0),
    price    DECIMAL NOT NULL DEFAULT 0 CHECK (price >= 0),
    currency VARCHAR(3) NOT NULL DEFAULT 'RSD',

    CONSTRAINT pk_package PRIMARY KEY (id)
);

CREATE TYPE package_dto AS (
    id BIGINT,
    name VARCHAR(255),
    duration INTEGER,
    price DECIMAL,
    currency VARCHAR(3)
);
