CREATE TABLE IF NOT EXISTS membership
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    member_id  BIGINT NOT NULL,
    package_id BIGINT NOT NULL,
    start_date DATE NOT NULL DEFAULT CURRENT_DATE,
    end_date   DATE NOT NULL DEFAULT CURRENT_DATE + 1,

    CONSTRAINT pk_memberships PRIMARY KEY (id),
    CONSTRAINT fk_member_id FOREIGN KEY (member_id) REFERENCES member (id) ON DELETE CASCADE,
    CONSTRAINT fk_package_id FOREIGN KEY (package_id) REFERENCES package (id) ON DELETE CASCADE
);
